package zuul;

public enum RoomId {
    ENTRANCE, COOKIE_ROOM, CAVE, TREASURE_ROOM, DARKROOM, LOBBY, WEAPON_ROOM, JAIL, READING_ROOM, SECRET_ROOM,
    EXIT1, EXIT2, EXIT3, EXIT4, EXIT5, EXIT6, EXIT7
}
