name: Code Format Check Front End

on:
  push:
    branches: [ "master", "linrifen" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  code_format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      
      - name: print info
        run: echo currentdir
      
      - name: get current info
        run: pwd
      
      - name: change directory
        run: cd ./vue-zuul
      
      - name: Install dependencies
        run: npm install

      - name: Code Format Check
        run: npm run lint
