name: Code Format Check Front End

on:
  push:
    branches: [ "master", "linrifen" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  code_format_check:
    runs-on: ubuntu-latest

    steps:
      - name: get current info1
        run: pwd
      
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ref: linrifen
      
      - name: get current info2
        run: pwd
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
          
      - name: get current info3
        run: pwd
        
      - name: show branch
        run: git branch -a
      
      - name: list
        run: ls -a
        
      - name: print git version
        run: git --version
        
      - name: change branch
        run: git checkout linrifen
        
      - name: print info
        run: echo currentdir
      
      - name: get current info
        run: pwd
      
      - name: change directory
        run: cd ./vue-zuul
      
      - name: Install dependencies
        run: npm install

      - name: Code Format Check
        run: npm run lint
